webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetector.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionEvent.java
As I suggested in the issue #305 I've added references to BufferedImages to the WebcamMotionEvent class.
I added new constructor and kept the old one for backward compatibility.
Also WebcamMotionDetector contains some related changes. There are some new BufferedImage references, so I renamed them to keep their purpose clear.
=> WebcamMotionEvent: Added references to current image and previous image

webcam-capture/src/main/java/com/github/sarxos/webcam/Webcam.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamUpdater.java
Here is the first pull request regarding the issue #307 
I imported the format.xml to the eclipse, so i hope the formatting is ok.
=> Customizable WebcamUpdater; issue #307

webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetector.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetectorAlgorithm.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetectorDefaultAlgorithm.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamUpdater.java
Customizable WebcamMotionDetector according to #307.
This time I extracted the interface and class to the package level, otherwise the WebcamMotionDetector class would be too complex.
Public constructors/methods of the WebcamMotionDetector are untouched, I've just added one constructor and getDetectorAlgorithm() method, so the listener may get algorithm instance by calling
event.getSource().getDetectorAlgorithm()
=> Customizable WebcamMotionDetector

webcam-capture/src/main/java/com/github/sarxos/webcam/Webcam.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamDevice.java
I'll commit FsWebcamDevice changes later.
=> issue #307 - passing parameters to WebcamDevice instances

webcam-capture/src/example/java/MultipointMotionDetectionExample.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetector.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetectorAlgorithm.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetectorDefaultAlgorithm.java, webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionEvent.java
Adds support for multiple points when using motion detection.
It has a range and max variable to be able to decrease/increase the amount of points that are detected
Since without this you can only get one accurate position at a time when detecting motion this will allow to look for multiple positions at the same time.
Someelse should probably look through this since i am not too experienced in java and specially not in this area but it seems to be working from what i have tested.
=> Added support for multiple points for source of motion

webcam-capture-drivers/driver-v4l4j/src/main/java/com/github/sarxos/webcam/ds/v4l4j/V4l4jDevice.java
Firstly thanks for the great lib, really appreciate your efforts.
I've got USB working great on the Pi, but not the camera mod, which you're already aware of.
I'm hoping to work around #382 some other way besides hard reboot, right now I only need stills so maybe I can set the v4l2-ctl up to avoid this.
Please let me know if you have any ideas.
This PR is a quickfix for the timeout logs, currently printing;
2015-10-26 05:28:25,475 [atomic-processor-1] ERROR com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice - UNable to get image in {} seconds timeout
=> Log V4l4jDevice timeout

.gitignore, webcam-capture-examples/webcam-capture-onejar/pom.xml
I think it worth to add IntelliJ IDEA project files to ```.gitignore```.
Another commit fixes incorrect webcam-capture dependency version in onejar example.
=> Intellij IDEA project files in .gitignore

webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamDiscoveryService.java
While testing a new webcam driver that I wrote, I came across an NPE during the call to `Webcam.setDriver()`
=> Fix NPE in WebcamDiscoveryService

webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetectorDefaultAlgorithm.java
Just was going through and saw that the javadoc was copied and pasted to the next field without being edited to be correct. Simple change.
=> Fix copy-and-paste typo in javadoc

webcam-capture-drivers/driver-screencapture/src/main/java/com/github/sarxos/webcam/ds/gstreamer/ScreenCaptureDevice.java
It might be useful the adapt the resolution of a captured screen as one would be able with a normal camera.
=> Allow resolution adaption of the captured screen

webcam-capture-drivers/driver-openimaj/pom.xml
https://github.com/sarxos/webcam-capture/issues/653
=> #653 Fix dependency conflict issue for com.nativelibs4java:bridj:jar 

webcam-capture-addons/webcam-capture-addon-swt/pom.xml, webcam-capture-examples/webcam-capture-live-streaming/pom.xml, webcam-capture-examples/webcam-capture-swt-awt/pom.xml, webcam-capture-examples/webcam-capture-video-recording/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

webcam-capture-drivers/driver-openimaj/pom.xml
Hello, I noticed that the transitive dependency `com.google.android.tools:dx` can be safely excluded from direct dependency `com.nativelibs4java:bridj`  in module `webcam-capture-driver-openimaj`. This makes the dependency tree of the module slimmer.
=> Exclude unused transitive dependency

webcam-capture/src/example/java/CalculateFPSExample.java
Remove redundant initialization. We don't need to initialize t1 and t2 to a value since below k and p are explicitly defined in for loop and there's no other implicit conditions that may cause an runtime error if t1 and t2 are not initialized
=> Remove redundant initialization

webcam-capture/src/test/java/com/github/sarxos/webcam/WebcamPanelTest.java
This is a test refactoring
**Problem:**
The Magic Number Test occurs when assert() statements in a test method contain numeric literals (i.e., magic numbers) as parameters.
**Solution:**
As magic numbers do not indicate the meaning/purpose of the number, they should be replaced with constants or variables, thereby providing a descriptive name for the input.
**Result:**
- Before:
Assertions
.assertThat(d.getWidth())
.isEqualTo(256);
Assertions
.assertThat(d.getHeight())
.isEqualTo(345);
- After:
private final int WIDTH= 256;
private final int HEIGTH = 345;
Assertions
.assertThat(d.getWidth())
.isEqualTo(WIDTH);
Assertions
.assertThat(d.getHeight())
.isEqualTo(HEIGHT);
=> Test improvement

README.md
In the rationale section, the first line is written as, " Assume situation when your code depends on some capturing framework, but suddenly you have to drop it and use different, maybe newer one (e.g. replace archaic JMF with newest GStreamer)."
This line contains a typo error.This could be corrected and written as, "Assume **a** situation when your code depends on some capturing framework, but suddenly you have to drop it and use **a** different, maybe newer one (e.g. replace archaic JMF with newest GStreamer).
In the same Rationale paragraph, the third line is written as, " This is where Webcam Capture API comes to save the world - it was created to remove the burden of such situations so you do not have to rewrite your code never again, but instead you can simply switch the driver …
=> Typo errors fixed.

webcam-capture-examples/webcam-capture-javafx/README.md, webcam-capture-examples/webcam-capture-javafx/pom.xml
This PR makes the javafx capture demo up to date with more recent JavaFX versions (e.g. JavaFX 18.0.1).
Fixes #863
=> Make the JavaFX demo sample work with a more recent version of JavaFX

.github/workflows/maven.yml
* Linux and macOS only 
* Linux and macOS builds are currently failing, but PR #840 will fix them.
* Windows fails even with PR #840, so is not included in the matrix for now
=> Add Github Actions workflow for maven build

webcam-capture-drivers/driver-openimaj/pom.xml
* This is better for security reasons
* Recent Maven (e.g. 3.8.1) will block http url by default
=> driver-openimaj/pom.xml: use https for maven.openimaj.org

webcam-capture-examples/webcam-capture-websockets/pom.xml
Upgrade jetty-all from 9.2.7.v20150116 to 9.2.27.v20190403 for vulnerability fix:
- [CVE-2015-2080](https://www.oscs1024.com/hd/MPS-2016-5010)
- [CVE-2019-10241](https://www.oscs1024.com/hd/MPS-2019-4268)
=> fix(sec): upgrade jetty-all to 9.2.27.v20190403

webcam-capture/src/main/java/com/github/sarxos/webcam/Webcam.java
Scenario:
1. Connect webcam
2. Disconnect webcam
3. Connect webcam again
Before fixing this bug; (3) would fail, because when it tries to open the webcam again, it will notice that the webcam was never unlocked. You would need to turn the program off then on again in order to connect to that webcam again.
I discovered and fixed this bug in my Kotlin port of this project:
https://github.com/Kietyo/webcam-capture-kotlin/commit/935add096f1bc76ddd664c79d0e7a8563727434a
=> Fix bug where webcam did not unlock during dispose.
